# Generated by Django 5.2.17 on 2026-08-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0003_migrate_languages_options'),
    ]

    # Existing PostgreSQL JSONB columns already have the desired database shape.
    # Update migration state only so this framework upgrade remains schema-neutral.
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='sysoptions',
                    name='value',
                    field=models.JSONField(),
                ),
            ],
        ),
    ]
