# Generated by Django 5.2.17 on 2026-08-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0012_auto_20180501_0436'),
    ]

    # Existing PostgreSQL JSONB columns already have the desired database shape.
    # Update migration state only so this framework upgrade remains schema-neutral.
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='submission',
                    name='info',
                    field=models.JSONField(default=dict),
                ),
                migrations.AlterField(
                    model_name='submission',
                    name='statistic_info',
                    field=models.JSONField(default=dict),
                ),
            ],
        ),
    ]
