# Generated by Django 5.2.17 on 2026-08-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_userprofile_language'),
    ]

    # Existing PostgreSQL JSONB columns already have the desired database shape.
    # Update migration state only so this framework upgrade remains schema-neutral.
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='user',
                    name='session_keys',
                    field=models.JSONField(default=list),
                ),
                migrations.AlterField(
                    model_name='userprofile',
                    name='acm_problems_status',
                    field=models.JSONField(default=dict),
                ),
                migrations.AlterField(
                    model_name='userprofile',
                    name='oi_problems_status',
                    field=models.JSONField(default=dict),
                ),
            ],
        ),
    ]
