"""
Django settings for oj project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""
import os
from copy import deepcopy

import sentry_sdk

from utils.shortcuts import get_env

production_env = get_env("OJ_ENV", "dev") == "production"
if production_env:
    from .production_settings import *
else:
    from .dev_settings import *

secret_key_path = os.path.join(DATA_DIR, "config", "secret.key")
with open(secret_key_path, "r", encoding="utf-8") as f:
    SECRET_KEY = f.read().strip()
if not SECRET_KEY:
    raise RuntimeError("Django secret key file is empty")

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Applications
VENDOR_APPS = [
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.contenttypes',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_dramatiq',
    'django_dbconn_retry',
]


LOCAL_APPS = [
    'account',
    'announcement',
    'conf',
    'problem',
    'contest',
    'utils',
    'submission',
    'options',
    'judge',
]

INSTALLED_APPS = VENDOR_APPS + LOCAL_APPS

MIDDLEWARE = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'account.middleware.APITokenAuthMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'account.middleware.AdminRoleRequiredMiddleware',
    'account.middleware.SessionRecordMiddleware',
    # 'account.middleware.LogSqlMiddleware',
)
ROOT_URLCONF = 'oj.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
WSGI_APPLICATION = 'oj.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/public/'

AUTH_USER_MODEL = 'account.User'

TEST_CASE_DIR = os.path.join(DATA_DIR, "test_case")
LOG_PATH = os.path.join(DATA_DIR, "log")

AVATAR_URI_PREFIX = "/public/avatar"
AVATAR_UPLOAD_DIR = f"{DATA_DIR}{AVATAR_URI_PREFIX}"

UPLOAD_PREFIX = "/public/upload"
UPLOAD_DIR = f"{DATA_DIR}{UPLOAD_PREFIX}"

STATICFILES_DIRS = [os.path.join(DATA_DIR, "public")]


SENTRY_DSN = get_env('SENTRY_DSN', '')
if production_env and SENTRY_DSN:
    sentry_sdk.init(dsn=SENTRY_DSN)

LOGGING_HANDLERS = ['console']
LOGGING = {
   'version': 1,
   'disable_existing_loggers': False,
   'formatters': {
       'standard': {
           'format': '[%(asctime)s] - [%(levelname)s] - [%(name)s:%(lineno)d]  - %(message)s',
           'datefmt': '%Y-%m-%d %H:%M:%S'
       }
   },
   'handlers': {
       'console': {
           'level': 'DEBUG',
           'class': 'logging.StreamHandler',
           'formatter': 'standard'
       },
   },
   'loggers': {
       'django.request': {
           'handlers': LOGGING_HANDLERS,
           'level': 'ERROR',
           'propagate': True,
       },
       'django.db.backends': {
           'handlers': LOGGING_HANDLERS,
           'level': 'ERROR',
           'propagate': True,
       },
        'dramatiq': {
            'handlers': LOGGING_HANDLERS,
            'level': 'DEBUG',
            'propagate': False,
        },
       '': {
           'handlers': LOGGING_HANDLERS,
           'level': 'WARNING',
           'propagate': True,
       }
   },
}

REST_FRAMEWORK = {
    'TEST_REQUEST_DEFAULT_FORMAT': 'json',
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    )
}

REDIS_URL = "redis://%s:%s" % (REDIS_CONF["host"], REDIS_CONF["port"])


def redis_config(db):
    def make_key(key, key_prefix, version):
        return key

    return {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"{REDIS_URL}/{db}",
        "TIMEOUT": None,
        "KEY_PREFIX": "",
        "KEY_FUNCTION": make_key
    }


CACHES = {
    "default": redis_config(db=1)
}

SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"

DRAMATIQ_BROKER = {
    "BROKER": "dramatiq.brokers.redis.RedisBroker",
    "OPTIONS": {
        "url": f"{REDIS_URL}/4",
    },
    "MIDDLEWARE": [
        # "dramatiq.middleware.Prometheus",
        "dramatiq.middleware.AgeLimit",
        "dramatiq.middleware.TimeLimit",
        "dramatiq.middleware.Callbacks",
        "dramatiq.middleware.Retries",
        # "django_dramatiq.middleware.AdminMiddleware",
        "django_dramatiq.middleware.DbConnectionsMiddleware"
    ]
}

DRAMATIQ_RESULT_BACKEND = {
    "BACKEND": "dramatiq.results.backends.redis.RedisBackend",
    "BACKEND_OPTIONS": {
        "url": f"{REDIS_URL}/4",
    },
    "MIDDLEWARE_OPTIONS": {
        "result_ttl": None
    }
}

IP_HEADER = "HTTP_X_REAL_IP"

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'


def _env_bool(name, default):
    value = get_env(name, 'true' if default else 'false').strip().lower()
    if value not in {'true', 'false'}:
        raise RuntimeError(f'{name} must be true or false')
    return value == 'true'


def _env_int(name, default):
    value = get_env(name, str(default)).strip()
    try:
        return int(value)
    except ValueError as exc:
        raise RuntimeError(f'{name} must be an integer') from exc


AUTHENTIK_OIDC_ENABLED = _env_bool('AUTHENTIK_OIDC_ENABLED', False)
AUTHENTIK_LOCAL_LOGIN_ENABLED = _env_bool('AUTHENTIK_LOCAL_LOGIN_ENABLED', True)
AUTHENTIK_LOCAL_REGISTER_ENABLED = _env_bool('AUTHENTIK_LOCAL_REGISTER_ENABLED', True)
AUTHENTIK_OIDC_ISSUER = get_env(
    'AUTHENTIK_OIDC_ISSUER',
    'https://auth.icthub.top/application/o/xju-oj/',
).rstrip('/')
AUTHENTIK_OIDC_CLIENT_ID = get_env('AUTHENTIK_OIDC_CLIENT_ID', '').strip()
AUTHENTIK_OIDC_CLIENT_SECRET_FILE = get_env('AUTHENTIK_OIDC_CLIENT_SECRET_FILE', '/dev/null').strip()
AUTHENTIK_OIDC_REDIRECT_URI = get_env(
    'AUTHENTIK_OIDC_REDIRECT_URI',
    'https://oj.icthub.top/api/auth/oidc/callback/',
).strip()
AUTHENTIK_OIDC_REGISTER_URL = get_env(
    'AUTHENTIK_OIDC_REGISTER_URL',
    'https://auth.icthub.top/if/flow/icthub-xju-oj-registration/',
).strip()
AUTHENTIK_OIDC_POST_LOGOUT_REDIRECT_URI = get_env(
    'AUTHENTIK_OIDC_POST_LOGOUT_REDIRECT_URI',
    'https://oj.icthub.top',
).strip()
AUTHENTIK_OIDC_SCOPES = get_env('AUTHENTIK_OIDC_SCOPES', 'openid profile email groups').strip()
AUTHENTIK_OIDC_STATE_TTL_SECONDS = _env_int('AUTHENTIK_OIDC_STATE_TTL_SECONDS', 300)
AUTHENTIK_OIDC_CLOCK_SKEW_SECONDS = _env_int('AUTHENTIK_OIDC_CLOCK_SKEW_SECONDS', 60)
AUTHENTIK_OIDC_ALLOWED_ALGORITHMS = tuple(
    item for item in get_env('AUTHENTIK_OIDC_ALLOWED_ALGORITHMS', 'RS256').split() if item
)
