import {
  Activity,
  ArrowDown,
  ArrowDownToLine,
  BarChart3,
  Bell,
  BookOpen,
  CalendarDays,
  ChartNoAxesCombined,
  Check,
  ChevronDown,
  CircleHelp,
  Clipboard,
  Clock3,
  Copy,
  Download,
  FileText,
  HelpCircle,
  Grid2X2,
  Home,
  Info,
  LayoutDashboard,
  List,
  ListChecks,
  ListOrdered,
  LoaderCircle,
  LogOut,
  Menu,
  Medal,
  Megaphone,
  MessageCircle,
  MessagesSquare,
  MoreHorizontal,
  Pencil,
  Plus,
  PlayCircle,
  RefreshCw,
  Rocket,
  Search,
  Send,
  ServerCog,
  Settings,
  ShieldCheck,
  Sparkles,
  Tags,
  Trophy,
  Trash2,
  UserCircle,
  Users,
  Upload,
  Undo2,
  LockKeyhole,
  Lightbulb,
  Mail,
  Camera,
  Shuffle,
  Expand,
  X
} from 'lucide-vue-next'

const iconMap = {
  home: Home,
  'ios-home': Home,
  'ios-keypad': Grid2X2,
  keypad: Grid2X2,
  trophy: Trophy,
  'ios-pulse-strong': Activity,
  'ios-person-outline': UserCircle,
  'ios-locked-outline': LockKeyhole,
  'ios-lightbulb-outline': Lightbulb,
  'ios-email-outline': Mail,
  podium: Medal,
  'ios-analytics': ChartNoAxesCombined,
  chart: BarChart3,
  'stats-bars': BarChart3,
  'information-circled': Info,
  information: Info,
  'circle-help': CircleHelp,
  'ios-photos': BookOpen,
  'chatbubble-working': MessagesSquare,
  chatbubble: MessageCircle,
  navicon: List,
  'navicon-round': ListChecks,
  'arrow-down-b': ChevronDown,
  'ios-arrow-down': ArrowDown,
  search: Search,
  calendar: CalendarDays,
  'android-time': Clock3,
  clipboard: Clipboard,
  clone: Copy,
  copy: Copy,
  download: Download,
  edit: Pencil,
  send: Send,
  rocket: Rocket,
  loading: LoaderCircle,
  refresh: RefreshCw,
  tag: Tags,
  shuffle: Shuffle,
  plus: Plus,
  trash: Trash2,
  upload: Upload,
  undo: Undo2,
  'arrow-down': ArrowDownToLine,
  'question-circle': HelpCircle,
  expand: Expand,
  camera: Camera,
  close: X,
  check: Check,
  bell: Bell,
  megaphone: Megaphone,
  settings: Settings,
  'dashboard': LayoutDashboard,
  'fa-dashboard': LayoutDashboard,
  menu: Menu,
  bars: List,
  'list-ol': ListOrdered,
  'info-circle': Info,
  users: Users,
  'fa-trophy': Trophy,
  'fa-bars': List,
  'fa-server': ServerCog,
  'server-cog': ServerCog,
  'file-text': FileText,
  'play-circle': PlayCircle,
  shield: ShieldCheck,
  sparkles: Sparkles,
  more: MoreHorizontal,
  logout: LogOut,
  'fa-sign-out': LogOut,
  user: UserCircle,
  'user-circle': UserCircle,
  'fa-user': UserCircle,
  'fa-cog': Settings,
  'fa-bell': Bell,
  'fa-list': List
}

export function resolveIcon (type) {
  return iconMap[type] || Sparkles
}

export default iconMap
