# Generated by Django 5.2.17 on 2026-08-24 17:43

import problem.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0014_problem_share_submission'),
    ]

    # Existing PostgreSQL JSONB columns already have the desired database shape.
    # Update migration state only so this framework upgrade remains schema-neutral.
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='problem',
                    name='io_mode',
                    field=models.JSONField(default=problem.models._default_io_mode),
                ),
                migrations.AlterField(
                    model_name='problem',
                    name='languages',
                    field=models.JSONField(),
                ),
                migrations.AlterField(
                    model_name='problem',
                    name='samples',
                    field=models.JSONField(),
                ),
                migrations.AlterField(
                    model_name='problem',
                    name='statistic_info',
                    field=models.JSONField(default=dict),
                ),
                migrations.AlterField(
                    model_name='problem',
                    name='template',
                    field=models.JSONField(),
                ),
                migrations.AlterField(
                    model_name='problem',
                    name='test_case_score',
                    field=models.JSONField(),
                ),
            ],
        ),
    ]
